with open('inference.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_class = []
new_class.append("class SecurityAgentBaseline:\n")
new_class.append("    def __init__(self):\n")
new_class.append("        self.env = AiSecurityEnv()\n")
new_class.append("\n")
new_class.append("    def run_episode(self, task_id=None):\n")
new_class.append("        state = self.env.reset()\n")
new_class.append("        action = self.decide(state)\n")
new_class.append("        observation, reward, done, info = self.env.step(action)\n")
new_class.append("        success = reward >= 0.8\n")
new_class.append("        return dict(task=state.get('event_id'), state=state, action=action,\n")
new_class.append("                    reward=reward, observation=observation, done=done,\n")
new_class.append("                    success=success, grade=info.get('grade'))\n")
new_class.append("\n")
new_class.append("    def decide(self, state):\n")
new_class.append("        logs = state.get('logs', [])\n")
new_class.append("        data_sensitivity = state.get('data_sensitivity', 'low')\n")
new_class.append("        logs_text = ' '.join(logs).lower()\n")
new_class.append("        exfil_kw = ['exfiltrate', 'export', 'transfer', '2gb']\n")
new_class.append("        if any(kw in logs_text for kw in exfil_kw):\n")
new_class.append("            if data_sensitivity == 'high':\n")
new_class.append("                return dict(allow=False, threat_type='data_exfiltration',\n")
new_class.append("                            response_action='block')\n")
new_class.append("        failed = logs_text.count('failed login')\n")
new_class.append("        if 'failed login' in logs_text and failed >= 3:\n")
new_class.append("            rule = dict(rule_action='block', target='ip', duration='1h')\n")
new_class.append("            return dict(allow=False, threat_type='brute_force',\n")
new_class.append("                        response_action='block_ip', firewall_rule=rule)\n")
new_class.append("        time_kw = ['midnight', '02:', '03:']\n")
new_class.append("        anomalies = sum([\n")
new_class.append("            'unusual' in logs_text,\n")
new_class.append("            'unknown ip' in logs_text,\n")
new_class.append("            any(t in logs_text for t in time_kw),\n")
new_class.append("            'admin login' in logs_text,\n")
new_class.append("        ])\n")
new_class.append("        if anomalies >= 2:\n")
new_class.append("            rule = dict(rule_action='block', target='ip', duration='24h')\n")
new_class.append("            return dict(allow=False, threat_type='intrusion',\n")
new_class.append("                        response_action='block and alert', firewall_rule=rule)\n")
new_class.append("        return dict(allow=True, threat_type='none', response_action='allow')\n")
new_class.append("\n")
new_class.append("    def run_benchmark(self, num_episodes=10):\n")
new_class.append("        episodes, rewards, successes = [], [], 0\n")
new_class.append("        for _ in range(num_episodes):\n")
new_class.append("            ep = self.run_episode()\n")
new_class.append("            episodes.append(ep)\n")
new_class.append("            rewards.append(ep['reward'])\n")
new_class.append("            if ep['success']:\n")
new_class.append("                successes += 1\n")
new_class.append("        avg = sum(rewards) / len(rewards) if rewards else 0.0\n")
new_class.append("        return dict(total_episodes=num_episodes, successful=successes,\n")
new_class.append("                    failed=num_episodes - successes,\n")
new_class.append("                    success_rate=round(successes / num_episodes, 4),\n")
new_class.append("                    average_reward=round(avg, 4),\n")
new_class.append("                    episodes=episodes)\n")
new_class.append("\n")

out = lines[:177] + new_class + lines[337:]
with open('inference.py', 'w', encoding='utf-8') as f:
    f.writelines(out)
print('Done')
